language: python
python:
  - '3.7'
  - '3.8'

before_install:
    - sudo apt-get update
    - sudo apt-get install -y ffmpeg
    - pip install tox-travis coveralls

script: tox

after_success: coveralls
